manager/urls.py
from django.urls import path

from manager.views import (
    index,
    PositionListView,
    PositionDetailView,
    PositionCreateView,
    PositionUpdateView,
    PositionDeleteView,

    TaskTypeListView,
    TaskTypeCreateView,
    TaskTypeUpdateView,
    TaskTypeDetailView,
    TaskTypeDeleteView,

    WorkerListView,
    WorkerDetailView,
    WorkerCreateView,
    WorkerDeleteView,
    WorkerPositionUpdateView,

    TaskListView,
    TaskDetailView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    task_assign_unassign, logout_view, UserLoginView, logged_out_view,

)

urlpatterns = [
    path("", index, name="home"),
    path("position/", PositionListView.as_view(), name="position-list"),
    path("position/<int:pk>/detail/", PositionDetailView.as_view(), name="position-detail"),
    path("position/create/", PositionCreateView.as_view(), name="position-create"),
    path("position/<int:pk>/update/", PositionUpdateView.as_view(), name="position-update"),
    path("position/<int:pk>/delete/", PositionDeleteView.as_view(), name="position-delete"),

    path("tasktype/", TaskTypeListView.as_view(), name="task-type-list"),
    path("tasktype/<int:pk>/detail/", TaskTypeDetailView.as_view(), name="task-type-detail"),
    path("tasktype/create/", TaskTypeCreateView.as_view(), name="task-type-create"),
    path("tasktype/<int:pk>/update/", TaskTypeUpdateView.as_view(), name="task-type-update"),
    path("tasktype/<int:pk>/delete/", TaskTypeDeleteView.as_view(), name="task-type-delete"),

    path("worker/", WorkerListView.as_view(), name="worker-list"),
    path("worker/<int:pk>/detail/", WorkerDetailView.as_view(), name="worker-detail"),
    path("worker/create/", WorkerCreateView.as_view(), name="worker-create"),
    path("worker/<int:pk>/delete/", WorkerDeleteView.as_view(), name="worker-delete"),
    path("worker/<int:pk>/update/", WorkerPositionUpdateView.as_view(), name="worker-position-update"),

    path("task/", TaskListView.as_view(), name="task-list"),
    path("task/<int:pk>/detail/", TaskDetailView.as_view(), name="task-detail"),
    path("task/create/", TaskCreateView.as_view(), name="task-create"),
    path("task/<int:pk>/update/", TaskUpdateView.as_view(), name="task-update"),
    path("task/<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"),
    path("task/<int:pk>/assign_unassign/", task_assign_unassign, name="task-assign-unassign"),
    path('logged_out/', logged_out_view, name='logged_out'),
]


app_name = "manager"

templates/accounts/logged_out.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block header %}{% endblock header %}

{% block content %}

    <main>

        {% include 'includes/pre-loader.html' %}

        <!-- Section -->
        <section class="min-vh-100 d-flex align-items-center section-image overlay-soft-dark" data-background="{% static 'assets/img/pages/form-image.jpg' %}">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-12 d-flex align-items-center justify-content-center">
                        <div class="signin-inner my-4 my-lg-0 bg-white shadow-soft border rounded border-gray-300 p-4 p-lg-5 w-100 fmxw-500">
                            <div class="text-center text-md-center mb-4 mt-md-0">
                                <h1 class="mb-0 h3">You have been successfully logged out</h1>
                            </div>
                            <p class="text-center text-muted mb-4">
                                You have been logged out of your account. To log in again, click the button below.
                            </p>
                            <div class="d-grid">
                                <a href="{% url 'login' %}" class="btn btn-primary">Log in again</a>
                                <a href="{% url 'manager:home' %}" class="btn btn-primary mt-3">Go to home page</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

    </main>

{% endblock content %}

{% block footer %}{% endblock footer %}

templates/accounts/password_change_done.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block header %}{% endblock header %}

{% block content %}

    <main>

        {% include 'includes/pre-loader.html' %}

        <!-- Section -->
        <section class="min-vh-100 d-flex align-items-center section-image overlay-soft-dark" data-background="{% static 'assets/img/pages/form-image.jpg' %}">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-12 d-flex align-items-center justify-content-center">
                        <div class="signin-inner my-4 my-lg-0 bg-white shadow-soft border rounded border-gray-300 p-4 p-lg-5 w-100 fmxw-500">
                            <div class="text-center text-md-center mb-4 mt-md-0">
                                <h1 class="mb-0 h3">Password Changed</h1>
                            </div>
                            <span>Your password has been changed successfully. <br />
                              <a href="/">Go to home</a>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </main>

 {% endblock content %}

 {% block footer %}{% endblock footer %}

templates/accounts/sign-in.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block header %}{% endblock header %}

{% block content %}

    <main>
    

        <!-- Section -->
        <section class="min-vh-100 d-flex align-items-center section-image overlay-soft-dark" data-background="{% static 'assets/img/pages/form-image.jpg' %}">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-12 d-flex align-items-center justify-content-center">
                        <div class="signin-inner my-4 my-lg-0 bg-white shadow-soft border rounded border-gray-300 p-4 p-lg-5 w-100 fmxw-500">
                            <div class="text-center text-md-center mb-4 mt-md-0">
                                <h1 class="mb-0 h3">Sign in to our platform</h1>
                            </div>
                            <form method="post" class="mt-4">
                                {% csrf_token %}
                                <!-- Form -->
                                {% if form.non_field_errors %}
                                    {% for error in form.non_field_errors %}
                                        <span class="text-danger"> {{ error }} </span>
                                    {% endfor %}
                                {% endif %}
                                {% for field in form %}
                                <div class="form-group mb-4">
                                    <label for="email">{{ field.label }}</label>
                                    <div class="input-group">
                                        <span class="input-group-text" id="basic-addon1">
                                            <span class="fas {% if field.name == 'username' %} fa-user {% else %} fa-unlock-alt {% endif %}"></span>
                                        </span>
                                        {{ field }}
                                    </div>  
                                </div>
                                <span class="text-danger"> {{ field.errors }} </span>
                                {% endfor %}
                                <!-- End of Form -->
                                <div class="d-flex justify-content-between align-items-center mb-4">
                                    <div class="form-check mb-0">
                                        <input class="form-check-input" type="checkbox" value="" id="remember">
                                        <label class="form-check-label mb-0" for="remember">
                                            Remember me
                                        </label>
                                    </div>
                                    
                                </div>
                                <div class="d-grid">
                                    <button type="submit" class="btn btn-primary">Sign in</button>
                                </div>
                            </form>
                            
                            
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </main>

 {% endblock content %}

 {% block footer %}{% endblock footer %}