manager/urls.py
from django.urls import path

from manager.views import (
    index,
    PositionListView,
    PositionDetailView,
    PositionCreateView,
    PositionUpdateView,
    PositionDeleteView,

    TaskTypeListView,
    TaskTypeCreateView,
    TaskTypeUpdateView,
    TaskTypeDetailView,
    TaskTypeDeleteView,

    WorkerListView,
    WorkerDetailView,
    WorkerCreateView,
    WorkerDeleteView,
    WorkerPositionUpdateView,

    TaskListView,
    TaskDetailView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    task_assign_unassign, logout_view, UserLoginView, logged_out_view,

)

urlpatterns = [
    path("", index, name="home"),
    path("position/", PositionListView.as_view(), name="position-list"),
    path("position/<int:pk>/detail/", PositionDetailView.as_view(), name="position-detail"),
    path("position/create/", PositionCreateView.as_view(), name="position-create"),
    path("position/<int:pk>/update/", PositionUpdateView.as_view(), name="position-update"),
    path("position/<int:pk>/delete/", PositionDeleteView.as_view(), name="position-delete"),

    path("tasktype/", TaskTypeListView.as_view(), name="task-type-list"),
    path("tasktype/<int:pk>/detail/", TaskTypeDetailView.as_view(), name="task-type-detail"),
    path("tasktype/create/", TaskTypeCreateView.as_view(), name="task-type-create"),
    path("tasktype/<int:pk>/update/", TaskTypeUpdateView.as_view(), name="task-type-update"),
    path("tasktype/<int:pk>/delete/", TaskTypeDeleteView.as_view(), name="task-type-delete"),

    path("worker/", WorkerListView.as_view(), name="worker-list"),
    path("worker/<int:pk>/detail/", WorkerDetailView.as_view(), name="worker-detail"),
    path("worker/create/", WorkerCreateView.as_view(), name="worker-create"),
    path("worker/<int:pk>/delete/", WorkerDeleteView.as_view(), name="worker-delete"),
    path("worker/<int:pk>/update/", WorkerPositionUpdateView.as_view(), name="worker-position-update"),

    path("task/", TaskListView.as_view(), name="task-list"),
    path("task/<int:pk>/detail/", TaskDetailView.as_view(), name="task-detail"),
    path("task/create/", TaskCreateView.as_view(), name="task-create"),
    path("task/<int:pk>/update/", TaskUpdateView.as_view(), name="task-update"),
    path("task/<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"),
    path("task/<int:pk>/assign_unassign/", task_assign_unassign, name="task-assign-unassign"),
    path('logged_out/', logged_out_view, name='logged_out'),
]


app_name = "manager"

templates/includes/footer.html
{% load static %}

<footer class="footer pb-5 pt-5 bg-dark text-white mt-auto">
  <div class="container">
    <div class="row">

      <div class="col-md-6 mb-3">
        <h5 class="mb-3">About the Project</h5>
        <p>
          This web application was built for task management within a team.
          It allows you to assign workers, set deadlines, and track task priorities effectively.
        </p>
      </div>

      <div class="col-md-6 mb-3">
        <h5 class="mb-3">About the Developer</h5>
        <p>
          Hi! I'm Nazarii, a backend developer.
          This project is a part of my portfolio, developed using Django.
        </p>
        <p>
          Contact me: nazar131188@gmail.com <br>
          <a href="https://github.com/Carn1vor3" class="btn btn-icon-only btn-github" type="button" aria-label="GitHub button" title="GitHub">
            <span aria-hidden="true" class="fab fa-github"></span>
          </a>
          <a href="https://t.me/Carn1vor3" class="btn btn-icon-only btn-tertiary" type="button" aria-label="Telegram button" title="Telegram">
            <span aria-hidden="true" class="fab fa-telegram-plane"></span>
          </a>
          <a href="https://www.instagram.com/carn1vor3_/" class="btn btn-icon-only btn-instagram" type="button" aria-label="Instagram button" title="Instagram">
            <span aria-hidden="true" class="fab fa-instagram"></span>
          </a>
        </p>
      </div>

    </div>

    <hr class="bg-light my-4">

    <div class="text-center">
      <p class="mb-0">© {{ now|date:"Y" }} All rights reserved.</p>
    </div>
  </div>
</footer>

templates/includes/navigation.html
{% load static %}

<header class="header-global">
    {% if request.path == "/landing-freelancer/" or request.path == "/blank/" %}
    <nav id="navbar-main" aria-label="Primary navigation" class="navbar navbar-main navbar-expand-lg navbar-theme-primary headroom navbar-light navbar-theme-secondary">
    {% else %}
    <nav id="navbar-main" aria-label="Primary navigation" class="navbar navbar-main navbar-expand-lg navbar-theme-primary headroom navbar-dark navbar-theme-secondary">
    {% endif %}
      <div class="container position-relative">
          <a class="navbar-brand me-lg-5" href="/">
              <span class="fas fa-home" style="font-size: 2rem; color: #ffffff;"></span>
          </a>
          <div class="navbar-collapse collapse me-auto" id="navbar_global">
              <div class="navbar-collapse-header">
                  <div class="row">
                      <div class="col-6 collapse-brand">
                          <a href="/">
                              <img src="{% static 'assets/img/brand/dark.svg' %}" alt="Themesberg logo">
                          </a>
                      </div>
                      <div class="col-6 collapse-close">
                          <a href="#navbar_global" class="fas fa-times" data-bs-toggle="collapse" data-bs-target="#navbar_global" aria-controls="navbar_global" aria-expanded="false" title="close" aria-label="Toggle navigation"></a>
                      </div>
                  </div>
              </div>
              <ul class="navbar-nav navbar-nav-hover align-items-lg-center">
                  <li class="nav-item dropdown">
                      <a href="#" class="nav-link dropdown-toggle" id="frontPagesDropdown" aria-expanded="false" data-bs-toggle="dropdown">
                          Pages
                          <span class="fas fa-angle-down nav-link-arrow ms-1"></span>
                      </a>
                      <div class="dropdown-menu dropdown-megamenu px-0 py-2 p-lg-4" aria-labelledby="frontPagesDropdown">
                          <div class="row">
                              <div class="col-6 col-lg-4">
                                  <h6 class="d-block mb-3 text-primary">Main pages</h6>
                                  <ul class="list-style-none mb-4">
                                      <li class="mb-2 megamenu-item">
                                          <a class="megamenu-link" href="{% url 'manager:position-list' %}">Positions</a>
                                      </li>
                                      <li class="mb-2 megamenu-item">
                                          <a class="megamenu-link" href="{% url 'manager:task-list' %}">Tasks</a>
                                      </li>
                                      <li class="mb-2 megamenu-item">
                                          <a class="megamenu-link" href="{% url 'manager:task-type-list' %}">Types of Tasks</a>
                                      </li>
                                      <li class="mb-2 megamenu-item">
                                          <a class="megamenu-link" href="{% url 'manager:worker-list' %}">Workers</a>
                                      </li>
                                  </ul>
                              </div>
                              <div class="col-6 col-lg-4">
                                  <h6 class="d-block mb-3 text-primary">User</h6>
                                  <ul class="list-style-none mb-4">
                                    {% if request.user.is_authenticated %}
                                        <li class="mb-2 megamenu-item">
                                            <a class="megamenu-link" href="{% url 'logout' %}">Logout</a>
                                        </li>
                                    {% else %}
                                      <li class="mb-2 megamenu-item">
                                          <a class="megamenu-link" href="{% url 'login' %}">Sign in</a>
                                      </li>
                                    {% endif %}
                                  </ul>
                              </div>
                          </div>
                      </div>
                  </li>

                  <li class="nav-item dropdown">
                      <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown" id="supportDropdown" aria-expanded="false">
                          Support
                          <span class="fas fa-angle-down nav-link-arrow ms-1"></span>
                      </a>
                      <div class="dropdown-menu dropdown-menu-lg" aria-labelledby="supportDropdown">
                          <div class="col-auto px-0">
                              <div class="list-group list-group-flush">
                                  <a href="https://t.me/Carn1vor3" target="_blank" class="list-group-item list-group-item-action d-flex align-items-center p-0 py-3 px-lg-4">
                                      <span class="icon icon-sm"><span class="fas fa-microphone-alt"></span></span>
                                      <div class="ms-4">
                                          <span class="d-block font-small fw-bold mb-0">Support</span>
                                          <span class="small">Need help? Ask us!</span>
                                      </div>
                                  </a>
                              </div>
                          </div>
                      </div>
                  </li>
              </ul>
          </div>
          <div class="d-flex align-items-center">
            {% if request.user.is_authenticated %}
                <a href="{% url 'logout' %}"
                   class="btn btn-outline-gray-100 d-none d-lg-inline me-md-3"><span class="fas fa-sign-out-alt me-2"></span> Logout</a>
            {% else %}
                <a href="{% url 'login' %}"
                    class="btn btn-outline-gray-100 d-none d-lg-inline me-md-3"><span class="fas fa-sign-in-alt me-2"></span> Sign IN</a>
            {% endif %}
              <button class="navbar-toggler ms-2" type="button" data-bs-toggle="collapse" data-bs-target="#navbar_global" aria-controls="navbar_global" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
              </button>
          </div>
      </div>
  </nav>
</header>

templates/includes/pagination.html
{% load query_transform %}
{% if is_paginated %}
  <nav aria-label="Page navigation">
    <ul class="pagination justify-content-center mt-4">

      {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link rounded-pill shadow-sm px-3" href="?{% query_transform request page=page_obj.previous_page_number %}">&laquo; Prev</a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <span class="page-link rounded-pill shadow-sm px-3">&laquo; Prev</span>
        </li>
      {% endif %}

      {% for num in paginator.page_range %}
        {% if page_obj.number == num %}
          <li class="page-item active" aria-current="page">
            <span class="page-link rounded-pill shadow-sm px-3 bg-primary border-primary text-white">{{ num }}</span>
          </li>
        {% elif num > page_obj.number|add:"-3" and num < page_obj.number|add:"3" %}
          <li class="page-item">
            <a class="page-link rounded-pill shadow-sm px-3" href="?{% query_transform request page=num %}">{{ num }}</a>
          </li>
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link rounded-pill shadow-sm px-3" href="?{% query_transform request page=page_obj.next_page_number %}">Next &raquo;</a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <span class="page-link rounded-pill shadow-sm px-3">Next &raquo;</span>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}

templates/includes/pre-loader.html
<div class="preloader bg-dark flex-column justify-content-center align-items-center">
  <svg id="loader-logo" xmlns="http://www.w3.org/2000/svg" width="50" height="50" viewBox="0 0 64 78.4">
    <path fill="#fff" d="M10,0h1.2V11.2H0V10A10,10,0,0,1,10,0Z" />
    <rect fill="none" stroke="#fff" stroke-width="11.2" x="40" y="17.6" width="0" height="25.6" />
    <rect fill="none" stroke="#fff" stroke-opacity="0.4" stroke-width="11.2" x="23" y="35.2" width="0"
      height="25.6" />
    <path fill="#fff" d="M52.8,35.2H64V53.8a7,7,0,0,1-7,7H52.8V35.2Z" />
    <rect fill="none" stroke="#fff" stroke-width="11.2" x="6" y="52.8" width="0" height="25.6" />
    <path fill="#fff" d="M52.8,0H57a7,7,0,0,1,7,7h0v4.2H52.8V0Z" />
    <rect fill="none" stroke="#fff" stroke-opacity="0.4" stroke-width="11.2" x="57.8" y="17.6" width="0"
      height="11.2" />
    <rect fill="none" stroke="#fff" stroke-width="11.2" x="6" y="35.2" width="0" height="11.2" />
    <rect fill="none" stroke="#fff" stroke-width="11.2" x="40.2" y="49.6" width="0" height="11.2" />
    <path fill="#fff" d="M17.6,67.2H28.8v1.2a10,10,0,0,1-10,10H17.6V67.2Z" />
    <rect fill="none" stroke="#fff" stroke-opacity="0.4" stroke-width="28.8" x="31.6" width="0" height="11.2" />
    <rect fill="none" stroke="#fff" x="14" stroke-width="28.8" y="17.6" width="0" height="11.2" />
  </svg>
</div>

templates/includes/scripts.html
{% load static %}

<!-- Core -->
<script src="{% static 'assets/js/popper.min.js' %}"></script>
<script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
<script src="{% static 'assets/js/headroom.min.js' %}"></script>

<!-- Vendor JS -->
<script src="{% static 'assets/js/on-screen.umd.min.js' %}"></script>
<script src="{% static 'assets/js/jarallax.min.js' %}"></script>
<script src="{% static 'assets/js/smooth-scroll.polyfills.min.js' %}"></script>
<script src="{% static 'assets/js/vivus.min.js' %}"></script>
<script src="{% static 'assets/js/datepicker.min.js' %}"></script>

<script async defer src="https://buttons.github.io/buttons.js"></script>

<!-- Pixel JS -->
<script src="{% static 'assets/js/pixel.js' %}"></script>